### PR TITLE
monza spec

### PR DESCRIPTION
**Pull request by LionsHead**
Added the spec response example App Store server and receipt validation.

### CODE REVIEW

**Comment by LionsHead** [comment]
Use error 'NoMethodError: undefined method `zone' for Time:Class' - fix? need more tests for time purchase.

**Comment by gabrielgarza** [comment]
Thanks for the help @LionsHead 👍 

I didn't understand why `zone` was moved to the end of the line.
https://github.com/gabrielgarza/monza/pull/3/files#diff-be4066709b4b5333242635ce897f7504R42

For example:
```ruby
Time.zone.at(Time.now.to_i / 1000)
# => Sat, 17 Jan 1970 23:32:32 UTC +00:00 

# But with zone at the end
Time.at(Time.now.to_i / 1000).zone
=> "PST"
```

Time zone needs to be used with Ruby on Rails, are you using the gem outside without rails?

Ideally it would be great to support apps outside of Rails as well.

**Comment by LionsHead** [comment]
Yeap, running without rails. Let's try to fix time zone for working outside rails.  Can should try with method in_time_zone.

**Comment by gabrielgarza** [comment]
@LionsHead Thanks again. I merged and made some changes but Time.zone.at should be working now.

Checkout the changes and let me know what you think
https://github.com/gabrielgarza/monza/commits/master

**Pull request merged**
