### PR TITLE
Status response updates

### PR DESCRIPTION
**Pull request by peterkovacs**
Adding the latest updates from apple's documentation.

### CODE REVIEW

**Comment by gabrielgarza** [comment]
Thanks @peterkovacs will review this as soon as I get a chance 👍

**Comment by gabrielgarza** [comment]
@peterkovacs Thanks, reviewing this now. Do you have a link to the latest documentation updates?

**Comment by peterkovacs** [comment]
@gabrielgarza https://developer.apple.com/documentation/appstoreservernotifications/notification_type for the NotificationType constants and https://developer.apple.com/documentation/appstoreservernotifications/responsebody for the body of the pushed notification.

**Comment by gabrielgarza** [comment]
@peterkovacs thanks for the pull request and apologies for taking so long to review it this time! Will be faster next time

**Comment by peterkovacs** [comment]
Thank you for merging!

**Pull request merged**
