### PR TITLE
include json response in VerificationError

### PR DESCRIPTION
**Pull request by mattyr**
Pretty self-explanatory.  Useful for 21006 error code returns where you still want to easily inspect the returned receipt info.

### CODE REVIEW

**Comment by gabrielgarza** [comment]
thanks @mattyr I'll review this soon

**Comment by mattyr** [comment]
So I actually started dumping a bunch of additional commits into this branch -- I discovered a fair number of attribute mismatches, missing fields, etc.  It's become more of a "bring this up to date" pull request...

**Comment by gabrielgarza** [comment]
hey @mattyr having trouble locating the attribute mismatches, not sure if you are referring to changes in the iTunes API (which I can't find here https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW28) or mismatches in the gem? Thanks

**Comment by mattyr** [comment]
Sorry, it's been a while -- I think the cause for the discrepancies I was seeing was the source of the transaction data.  IE, results from the apple test servers was different than live, and the structure of receipt data would differ depending upon the type of transaction (recurring/one-time).  Sorry it's been a while.   You can probably just ignore this pull request.

**Comment by gabrielgarza** [comment]
No worries at all, thanks for taking the time to put together the PR. Next time I will get to this sooner!

**Pull request closed without merging**
